services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: dashboard-frontend-car-wash-admin
    container_name: dashboard-frontend-car-wash-admin
    ports:
      - "3001:3000"
    env_file:
      - .env
    working_dir: /usr/src/app
    command: npm start
